<?php
    echo $this->Html->script([
        'app/shared/jquery/jquery.min',
        'app/shared/jqueryUI/jquery-ui',
        _WEBSITE_URL . 'plugins/bootstrap/js/bootstrap.js',
        'app/shared/angular/angular.min',
        'app/shared/css_browser_selector.js',
        'app/shared/icheck/icheck.js',
        'app/shared/uiBootstrap/ui-bootstrap',
        'app/shared/ngAnimate/angular-animate.min',
        'app/shared/ngCookies/angular-cookies.min',
        'app/shared/uiRouter/angular-ui-router.min',
        'app/shared/stopEvent/stop-event',
        'app/shared/ngFileUpload/ng-file-upload-shim', 'app/shared/ngFileUpload/ng-file-upload',
        'app/shared/ngProgressBar/ng-progress-bar', 'app/shared/ngFileUploader/ng-file-uploader',
        'app/shared/dfaCustomControls/custom-controls', 'app/shared/loadingBar/loading-bar.js',
        'app/shared/iCheck/iCheck.js', 'app/shared/inputValidator/input-validator.js',
        'app/shared/ngMask/ng-mask.js', 'app/shared/angularLocalStorage/angular-local-storage.js',
        'app/shared/packageTracker/package-tracker.js', 'app/shared/logisticsGoogleMap/logistics-google-map.js',
        'app/shared/bootstrapColorpicker/bootstrap-colorpicker-module.js',
        'app/shared/customField/custom-field.js','app/shared/uiSortable/sortable.js',
        'app/appConfig', 'app/app',
        'app/components/home/home.module', 'app/components/home/home.controller','app/components/home/home.service',
        'app/components/shipment/shipment.module', 'app/components/shipment/shipment.controller','app/components/shipment/shipment.service',
        'app/components/packages/packages.module', 'app/components/packages/packages.controller','app/components/packages/packages.service', 
        'app/components/deliveries/deliveries.module', 'app/components/deliveries/deliveries.controller','app/components/deliveries/deliveries.service', 
        'app/components/confirmation/confirmation.module', 'app/components/confirmation/confirmation.controller','app/components/confirmation/confirmation.service', 
        'app/components/dashboard/dashboard.module', 'app/components/dashboard/dashboard.controller','app/components/dashboard/dashboard.service', 
        'app/components/shipmentLabels/shipmentLabels.module', 'app/components/shipmentLabels/shipmentLabels.controller','app/components/shipmentLabels/shipmentLabels.service', 
        'app/components/packingList/packingList.module', 'app/components/packingList/packingList.controller','app/components/packingList/packingList.service', 
        'app/components/area/area.module', 'app/components/area/area.controller','app/components/area/area.service', 
        'app/components/item/item.module', 'app/components/item/item.controller','app/components/item/item.service', 
        'app/components/courier/courier.module', 'app/components/courier/courier.controller','app/components/courier/courier.service', 
        'app/components/subscriptions/subscriptions.module', 'app/components/subscriptions/subscriptions.controller','app/components/subscriptions/subscriptions.service', 
        'app/components/userManagement/userManagement.module', 'app/components/userManagement/userManagement.controller','app/components/userManagement/userManagement.service', 
        'app/components/map/map.module', 'app/components/map/map.controller','app/components/map/map.service',
        'app/components/location/location.module', 'app/components/location/location.controller','app/components/location/location.service', 
        'app/components/configurations/configurations.module', 'app/components/configurations/configurations.controller','app/components/configurations/configurations.service', 
        'app/components/fieldOptions/fieldOptions.module', 'app/components/fieldOptions/fieldOptions.controller','app/components/fieldOptions/fieldOptions.service',
        'app/components/core/core.filter', 'app/components/core/core.controller', 'app/components/core/core.service', 'app/components/core/core.constant', 'app/components/core/core.config']);
